
import mongoose,{Schema, Types} from "mongoose";
const childSchema=new Schema({
    parentName:{
        type:String,
      required:true,
      min:3,
      max:100,
    },
    password:
    {
      type:String,
      required:true,
      min:7,
      max:30,
    },
    phone:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
        unique:true,
    },
    location:{
        type:String,
        required:true,

    },
    childName:
    {
        type:String,
        required:true,
        unique:true,
    },
    requestId:
    {
        type:Types.ObjectId,
        ref:"request",
        required:true,
    },
    region:
    {
        type:String,
        required:true,
    },
    groupId:
    {
        type:Types.ObjectId,
        ref:"group",
        default:null,
    },
    isActiveted:
    {
        type:Boolean,
        default:true,
    },
    resetCode:{
        type:String,
        required:false,
    },
    profilePicture:
    {
        type:{
              secure_url:
              {
                type:String,
                required:true,
              },
              public_id:
              {
                type:String,
                required:true,
              }
        },
    },
    busService:
    {
        type:Boolean,
        required:true,
    },
    bus:
    {
        type:Types.ObjectId,
        ref:"bus",
        default:null,
    },
    meals:
    {
        type:[{dayWeek:{type:Number,min:0,max:5},meal1:{type:Types.ObjectId,ref:"meal"},meal2:{type:Types.ObjectId,ref:"meal",}}],
        default:[{dayWeek:0,meal1:null,meal2:null},{dayWeek:1,meal1:null,meal2:null},{dayWeek:2,meal1:null,meal2:null},{dayWeek:3,meal1:null,meal2:null},{dayWeek:4,meal1:null,meal2:null},{dayWeek:5,meal1:null,meal2:null}],
    }
},{timestamps:true,toObject:{virtuals:true},toJSON:{virtuals:true},strictQuery:true});

const childrenModel=mongoose.model("children",childSchema);
export default childrenModel;

